services:

  frontend:
    environment:
      BACKEND_API_BASE_SSR: ${BACKEND_API_BASE_SSR}
      BACKEND_API_BASE_CLIENT: ${BACKEND_API_BASE_CLIENT}
    build:
      context: frontend/.
      dockerfile: Dockerfile.dev
    ports:
      - ${WEB_PORT}:3000
    working_dir: /frontend
    volumes:
      - ./frontend/:/frontend:delegated # improve speed for hot reloading
      - /frontend/node_modules
    command: ["npm", "run", "dev"]

    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: .
      args:
        ENV_TYPE: ${APP_ENV}
    volumes:
      - .:/backend
    ports:
      - ${API_PORT}:5000
    depends_on:
      - pgsql_db
    restart: always
    environment:
      DATABASE_URL: ${DB_CONNECTION}

  pgsql_db:
    container_name: pgsql_db
    image: postgres:17
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./pgsql:/var/lib/postgresql
      - ./database/init:/docker-entrypoint-initdb.d  # add this
    ports:
      - ${POSTGRES_PORT}:5432
    restart: always
